version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - myapp-net
    restart: on-failure

networks:
  myapp-net:
    driver: bridge